DAY-05

1. WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT 
SELECT DEPTNO,COUNT(DEPTNO)
FROM EMP
GROUP BY DEPTNO;

2. WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT.
SELECT DEPTNO,COUNT(DEPTNO)
FROM EMP 
WHERE JOB!='PRESIDENT'
GROUP BY DEPTNO;
select * from emp;

3. WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB.
select job, sum(sal) as total_salary
from emp
group by job;

4. WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT.
select deptno,count(deptno)
from emp
where job='manager'
group by deptno;

5.WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING
 THE EMPLOYEES OF DEPTNO 20.

select deptno,avg(sal) 
from emp
where deptno!=20
group by deptno;

6. WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE
EMPLOYEES WHO SALARY IS GREATER THAN 2000 IN EACH DEPT.

select deptno,count(deptno),avg(sal)
from emp
where sal>2000
group by deptno;

7.WAQDTD TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT.
select deptno,sum(sal),count(deptno)
from emp
where job='salesman'
group by deptno;

8. WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB.
select job,count(job),max(sal)
from emp
group by job;

9.WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
select deptno,max(sal)
from emp
group by deptno;

10. WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE.
select sal,count(sal)
from emp
group by sal;

11.WAQTD NUMBER OF EMPLOYEES HIREDATE ON THE SAME DAY IN THE SAME DEPARTMENT

select hiredate,deptno,count(*)
from emp
group by hiredate,deptno;

12.WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT

select sal ,deptno,count(*)
from emp
group by sal,deptno;

13.WAQTD NUMBER OF EMPLOYEES HAVING THE SAME NAME IN THE SAME DEPARTMENT
select count(*)
from emp
group by ename,deptno;

14.WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT AND
 HAVING THE SAME NAME

select count(*)
from emp
group by ename,sal,deptno;

15.WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT AND 
HIRED ON THE SAME DAY

select count(*)
from emp
group by sal,deptno,hiredate;
