-- DAY-09
-- SUB-QUERY--> THE QUERY WHICH IS WRITTEN INSIDE THE QUERY CALLED SUB QUERY.
-- OUTER QUERY (INNER QUERY)

-- CASE-1: WHENEVER THERE WILL BE THE UNKNOWN PRESENT IN THE QUESTION OR QUERY SO WE CAN USE SUB QUERY TO FIND THE KNOWN VALUE A SOME TABLE 

-- CASE-2: WHENEVER THERE WILL BE THE UNKNOWN PRESENT IN THE QUESTION OR QUERY SO WE CAN USE SUB-QUERY HTO FIND THE KNOWN VALUE WUTHIN DIFFRERENT TABLE 

-- CASE-1:

-- 1. WAQTD NAME,SAL OF THE EMPLOYEES EARNING MORE THAN ADAMS
-- SELECT ENAME ,SAL FROM EMP
-- WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='ADAMS');

-- 2. WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
-- SELECT ENAME ,SAL FROM EMP 
-- WHERE SAL<(SELECT SAL FROM EMP WHERE ENAME='KING');

-- 3.WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY 
-- ARE WORKING IN THE SAME DEPT AS JONES

-- SELECT ENAME,DEPTNO FROM EMP
-- WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='JONES');

-- 4.WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME 
-- DESIGNATION AS JAMES
-- SELECT ENAME, JOB FROM EMP 
-- WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='JAMES');

-- 5.WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL
-- THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN JAMES ANNUAL SALARY.

-- SELECT EMPNO,ENAME ,SAL*12 AS ANNUAL_SALARY FROM EMP
-- WHERE SAL*12>(SELECT SAL*12 FROM EMP WHERE ENAME ='JAMES'); 

-- 6.WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED 
-- BEFORE SCOTT
SELECT ENAME,HIREDATE FROM EMP
WHERE hiredate <(select hiredate from emp where ename='scott');

-- 7.WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED
--  AFTER THE PRESIDENT
-- SELECT ENAME, HIREDATE FROM EMP
-- WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE JOB='PRESIDENT');

-- 8. WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL
--  LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
-- SELECT ENAME,SAL FROM EMP 
-- WHERE SAL<(SELECT SAL FROM EMP WHERE EMPNO='7839'); 


-- 9.WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES 
-- ARE HIRED BEFORE MILLER

-- SELECT * FROM EMP 
-- WHERE HIREDATE <(SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');

-- 10. WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES 
-- ARE EARNING MORE THAN ALLEN

-- SELECT ENAME , EMPNO FROM EMP
-- WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='ALLEN'); 


