DAY-08
LIKE OPERATOR:
--> IT IS USED FOR PATTERN MATCHING 
1.'%'...> ACCEPT ANY NO. OF CHAR OR.. NO CHAR
2. '_'---> SINGLE NO. OF CHAR ONLY

................................................................................................

1.WAQTD THE DETAILS OF EMP WHERE NAME START WITH 'S'
SELECT * FROM EMP
WHERE ENAME LIKE 'S%';

2.WAQTD THE DETAILS OF EMP WHERE NAME END WITH 'S'
SELECT * FROM EMP
WHERE ENAME LIKE '%S';

3.WAQTD THE DETAILS OF EMP WHERE IN NAME HAVING 'A' IN 
SECOND POSITION

SELECT * FROM EMP
WHERE ENAME LIKE'_A%';


4.WAQTD THE ENAME OF EMP HAVING 'ER' IN LAST POSITION
SELECT * FROM EMP
WHERE ENAME LIKE '%ER';

5.WAQTD THE ENAME WHERE NAME  START WITH 'S' AND
END WITH 'T'
SELECT * FROM EMP
WHERE ENAME LIKE 'S%T';

6.WAQTD THE ENAME WHERE NAME HAVING
i.START WITH 'M' 
ii.'R' IN 3RD POSITION 
Iii. END WITH 'N'

SELECT * FROM EMP
WHERE ENAME LIKE'M_R%N';


ORDER BY :(ASCENDING AND DESCENDING )
1.WAQTD THE DETAILS OF EMP WHERE SAL IN ASCENDING ORDER
SELECT * FROM EMP
ORDER BY SAL ASC;

2.WAQTD THE DETAILS OF EMP WHERE SAL IN DESCENDING ORDER
SELECT * FROM EMP 
ORDER BY SAL DESC;

3.WAQTD THE DETAILS OF EMP WHERE ENAME IN ASCENDING ORDER
SELECT * FROM EMP
ORDER BY ENAME ASC;

4.WAQTD THE DETAILS OF EMP WHERE ENAME IN ASCENDING ORDER/DESCENDING
SELECT * FROM EMP 
ORDER BY ENAME DESC;

5.WAQTD THE DETAILS OF EMP WHERE JOB IN DESCEDING ORDER
AND SAL IN ASCENDING ORDER
SELECT JOB,SAL FROM EMP
ORDER BY JOB DESC,SAL ASC;

6.WAQTD THE DETAILS OF EMP WHERE JOB IN DESCEDING ORDER
, SAL IN DESCENDING ORDER AND DEPTNO IN ASC
SELECT JOB,SAL,DEPTNO FROM EMP
ORDER BY SAL DESC,SAL DESC, DEPTNO ASC;



